server:
  port: 8081
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://121.40.136.222:3306/cloud?useSSL=false&charactEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: c9734e026c853760
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: false
    service-url:
      #单机版
      defaultZone: http://localhost:7001/eureka
      # 集群版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8081  # 修改主机id
    prefer-ip-address: true  # 访问路径显示IP

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    object-wrapper-factory: com.baomidou.mybatisplus.extension.MybatisMapWrapperFactory
